module.exports = {
  initPokeBox: [
    {
      id: 1,
      species: "サンダー",
      species_en: "Zapdos",
      nickname: "さんだあ",
      ability: "せいでんき",
      nature: "おくびょう",
      item: "いのちのたま",
      eff_h: 0,
      eff_a: 0,
      eff_b: 4,
      eff_c: 252,
      eff_d: 0,
      eff_s: 252,
      move_1: "ボルトチェンジ",
      move_2: "ぼうふう",
      move_3: "ねっぷう",
      move_4: "はねやすめ",
      description: "A個体値0",
    },
    {
      id: 2,
      species: "ラッキー",
      species_en: "Chansey",
      nickname: "らっきい",
      ability: "しぜんかいふく",
      nature: "ずぶとい",
      item: "しんかのきせき",
      eff_h: 4,
      eff_a: 0,
      eff_b: 252,
      eff_c: 0,
      eff_d: 252,
      eff_s: 0,
      move_1: "ちきゅうなげ",
      move_2: "タマゴうみ",
      move_3: "ステルスロック",
      move_4: "うたう",
      description: "A個体値0",
    },
  ],
  newPokemon: {
    id: 3,
    species: "カイリュー",
    nickname: "かいりゅう",
    ability: "マルチスケイル",
    nature: "わんぱく",
    item: "アッキのみ",
    eff_h: 196,
    eff_b: 204,
    eff_s: 108,
    move_1: "ダブルウイング",
    move_2: "ワイドブレイカー",
    move_3: "りゅうのまい",
    move_4: "はねやすめ",
    description: "H実数値191、S+1で最速ウツロイド抜き",
  },
  registeredPokemon: {
    id: 3,
    species: "カイリュー",
    species_en: "Dragonite",
    nickname: "かいりゅう",
    ability: "マルチスケイル",
    nature: "わんぱく",
    item: "アッキのみ",
    eff_h: 196,
    eff_a: 0,
    eff_b: 204,
    eff_c: 0,
    eff_d: 0,
    eff_s: 108,
    move_1: "ダブルウイング",
    move_2: "ワイドブレイカー",
    move_3: "りゅうのまい",
    move_4: "はねやすめ",
    description: "H実数値191、S+1で最速ウツロイド抜き",
  },
};

// module.exports = { initPokeBox };
